### ISSUE TITLE
Wire 3 checklist

### ISSUE THREAD

**Issue by Egorand** [square/wire#1016]
- [x] Publish RC1 - @Egorand  
- [x] Artifact ID should stay the same for Wire 3 (#1093) - @Egorand 
- [x] Add RELEASING.md - @Egorand 
- [x] expect/actual ProtoAdapter to preserve backwards compatibility (#1019) - @Egorand 
- [x] Incorrect semantics of default field values (#1006) - @Egorand 
- [x] Generated gRPC code doesn't compile with Java 12 (#1003) - @oldergod 
- [x] Kotlin generator assigns nullable refs to non-nullable variables in Java interop mode (#997) - @Egorand 
- [x] Fix gRPC APIs (#964) - @oldergod 
- [x] ~gRPC Server API codegen (#957) - @oldergod~
- [x] Documentation for gRPC code generation. (#946) - @oldergod 
- [ ] ~Explore plugin redesign to avoid using project.afterEvaluate (#889) - @jrodbx~ 
- [ ] ~Multi-platform support (Kotlin/Native) (#880) - @Egorand~
- [ ] Android Support for Gradle Plugin (#881) - @jrodbx 
- [x] GrpcTest#cancelChannel is flaky (#876) - @oldergod 
- [x] In wire-schema, change dependency on Guava back to "api" (#1030) - @Egorand 
- [x] expect/actual EnumAdapter to fix backwards compatibility (#1031) - @Egorand 
- [x] Add Experimental annotations to coroutines-based gRPC API (#1151) - @Egorand 
- [ ] Add Experimental annotations to multiplatform runtime (#1152) - @Egorand 
- [ ] Update README (#1029)

**Comment by Egorand** [comment]
Wire 3 has been released!
