### ISSUE TITLE
proto3 Working Document

### ISSUE THREAD

**Issue by swankjesse** [square/wire#279]
As kicked off by [issue 210](https://github.com/square/wire/issues/210), here’s what we need for proto3:
- [x] Forbid `optional` / `required` labels
- [x] First enum value with tag 0 (#575)
  - [x] Default Java enums to that value
  - [x] Forbid null for Java enums
- [x] `Any`
  - [x] support in parser (TODO oldergod: update)
  - [x] support in schema
  - [x] code gen and runtime API (requires `google/protobuf/any.proto`)
  - [x] serialization & deserialization
- [x] `map`
  - [x] support in parser
  - [x] support in schema (#578)
  - [x] code gen and runtime API (#596)
  - [x] serialization & deserialization (#596)
- [x] `Timestamp` and `Duration` (#1382)
  - [x] code gen and runtime API (`timestamp.proto,` `duration.proto`)
  - [x] serialization & deserialization
- [x] Packed is default for repeated scalars (#1383)
- [x] `reserved`
  - [x] support in parser (#548)
  - [x] support enforcement in schema (#283)
- [x] `stream` keyword for RPC response types (#282, #580)
- [x] No extensions unless it's a custom option. (#1384)
- [x] ~No unknown fields~ They got reverted in 3.5.
- [x] Forbid user-defined default values (#1385)
- [x] Scalars become non-nullable, but message fields remain nullable. (#1386)
  - Test case: empty string, default enum, 0 int in a repeated field should all be encoded.
  - Test case: map entries that have default values.
- [x] Support in Java.
  - [x] Crash if we pass a null to a non-nullable type (like `int32`)
  - [x] Default Java strings to ""
  - [x] Forbid null for Java strings
- [x] Support in Gson.
- [x] Tests for Gson and proto3.
- [x] Tests for Java and proto3.
- [x] AnyMessage documentation. (@oldergod)
- [x] Wrappers. (@swankjesse and @oldergod)
  - [x] Runtime.
  - [x] JSON.
- [x] JSON support.
  - [x] Moshi release for custom keys (@swankjesse to cut Moshi release) 
  - [x] MapAdapters. (@swankjesse)
    - [x] Unignore `WireJsonTest#wrappers()`.
    - [x] Map values in Gson (@swankjesse).
- [x] Create a doc to list differences we took in designing our generated code differently from Google. (@oldergod)
- [x] Proto2 and Proto3 interoperability tests. (@oldergod)
- [x] Remove proto3 unsupported option. (@oldergod)
- [x] Forbid usage for proto2 enums in proto3 messages. (@oldergod)

Goal: All done September 1?

**Comment by vanvlack** [comment]
@swankjesse looks like proto3 support got bumped to `2.1`?

**Comment by swankjesse** [comment]
That's our current plan. What features of proto3 are you most excited about?!

**Comment by vanvlack** [comment]
@swankjesse all the things. JSON support will be cool, but not having to rely on `optional/required` will be cool.

**Comment by rzimmer** [comment]
@swankjesse Support for _Any_ to replace removed extension support would be great.

**Comment by vanvlack** [comment]
@swankjesse now that proto3 is offifcial, what's the timeline on Wire supporting it in full?

**Comment by swankjesse** [comment]
I can't promise any specific timelines.

Proto3 requires some big changes to the runtime. We’ll need to use `int` instead of `Integer` for example, which may complicate some things. It's also not easy to migrate from proto2 to proto3, which will allow our urgency to migrate.

**Comment by vanvlack** [comment]
> It's also not easy to migrate from proto2 to proto3

Understandable. Would you think about selectively supporting proto3 syntax/features over time, vs a large push?

**Comment by JakeWharton** [comment]
We're already doing that.

**Comment by vanvlack** [comment]
> We're already doing that. -- @JakeWharton 

Do you have a priority list around what you are pulling in or when? I ask as some things like the following would be nice to see at some point:

- `First enum value with tag 0`
- `Timestamp and Duration`
- `JSON support`

**Comment by ShreyK** [comment]
Are you continuing to add support for proto3?

**Comment by JakeWharton** [comment]
We continue to plan to add support for proto3. Unfortunately there's not a
lot of momentum around it.

**Comment by jverne** [comment]
What would "JSON Support" provide when working with, say, Retrofit? Putting aside the data representation specifics (i.e., maps) who is the target audience?

I _think_ this means that we could use Wire directly as the Retrofit convertor (instead of using Wire to create classes that are then consumed by something like GsonConvertorFactory). That is, I could more closely model the JSON that is the source of the truth, and not have to worry what happens if Gson can't grok something.

I fully admit I might be missing the point, but if this is the general gist then I vote JSON support.

**Comment by swankjesse** [comment]
I’ve got reservations around proto3’s JSON mapping. It’s not completely trivial, and also incompatible with the way Wire does Gson. For example, it recommends mapping `field_name` to `fieldName` which I think is needless complexity.

... I’ve also got more general reservations around proto3. It conflates absent with zero, which is very incompatible with proto2.

**Comment by jverne** [comment]
Yeah, I'm not a fan of the name mangling. My proto, which I use to create classes from a very complicated JSON structure (like over 10k lines of generated code) uses the exact field names, and ideally I wouldn't have to change that.

I'm OK with wire just being a build step.   I'm just wondering what the other wins are for JSON support.

**Comment by fluxxion82** [comment]
I ran into a problem with using the proto3 schema, which you may already be aware of. Absent String fields are still trying to get encoded and this is causing a NPE.

**Comment by rick-kln** [comment]
Does the above issue still reflect the current status of proto3 on wire?

**Comment by swankjesse** [comment]
We’re going to resume work on it.

**Comment by DHosseiny** [comment]
Scalars become non-nullable, but message fields remain nullable.

**Comment by dkiefner** [comment]
Hello, do you have a timeline/roadmap when proto3 support will be available? We're about to assess if we want to wait for Wire3 to be released or using Googles runtime with protobuf-javalite to use proto3 in our apps 🙂

**Comment by swankjesse** [comment]
I think proto3 is a regression. We aren't rushing to support it in Wire.

**Comment by rick-kln** [comment]
If you're not actively working on supporting it, it might be best to close this issue and document that status in the README? We delayed a project to remove wire from our app based on the previous message here, in September, that yall were resuming work on proto3. Given the news that you're actually not working in it we probably have to take another look at moving away from wire and I'm sure the information could be similarly helpful to others.

**Comment by swankjesse** [comment]
Sorry for the thrash, we’re trying to find a nice way forward. The surface-level differences between proto2 and proto3 are small, but the behavior-level consequences are very large.

**Comment by rick-kln** [comment]
No problem, thanks for making open source stuff 😃 

Agree that the "behavior-level consequences are very large". That is the problem for us, as on iOS/Web/Backend/API levels we use proto3, on Android we ended up with proto2 because the team went with wire not realizing how big this gap is. This does cause us issues every now and then and the choice is basically waiting for wire to add proto3 or moving away from it.

**Comment by malachid** [comment]
Is the checklist in the description currently up-to-date?

**Comment by mellster2012** [comment]
+1 for full proto3 support - thank you!

**Comment by Clement-Jean** [comment]
How can I start helping on that ?

**Comment by sweetbot** [comment]
Are we still expecting proto3 support in Q1 2020? If not any time soon, could you please suggest an alternative solution to Wire, for generating Kotlin files from proto3 files in Android project during compile time? Because all of our backend system and iOS are using proto3. Thanks.

**Comment by ZacSweers** [comment]
@sweetbot nothing in this thread said "Q1 2020"

**Comment by garyp** [comment]
@sweetbot You might want to check out https://github.com/streem/pbandk (disclaimer: I'm one of the developers). It supports proto3 and generates Kotlin multiplatform code (currently supports Kotlin/JVM and Kotlin/JS; Kotlin/Native is still to do). It's not as mature as Wire, but we'd love some community contributions! We use it in production and all of the basic protobuf features are supported.

**Comment by kalyaganov** [comment]
Hello guys! Any update on this?

**Comment by nlgtuankiet** [comment]
Please don't thumb down me :(  I just want to know when this release or there is any pre-release version that we can try at this time

**Comment by JakeWharton** [comment]
Updates about the availability of proto3 will be posted when they are ready. Feel free to hit "subscribe" on the issue to be notified of such events. Until then, asking will yield no response.

**Comment by nlgtuankiet** [comment]
Thank you guys for all the hard work, we all appreciate it

**Comment by sweetbot** [comment]
Hooray! I think the announcement is pretty close.

**Comment by yschimke** [comment]
Not sure where to put some random trivia, so stuffing it here for google to index.  I ended up talking to a server using Jackson, using wire/proto3.  It ends up being a very atypical situation where the java kotlin class uses "parsed_command", but the proto3 json uses "parsedCommand".  Common sense would suggest the opposite is more common.  Anyway for Jackson I needed this to fix the handling of the wire code generated classes.

```
class WireProto3PropertyNamingStrategy : PropertyNamingStrategy.PropertyNamingStrategyBase() {
  override fun translate(propertyName: String): String {
    if (propertyName.contains('_')) {
      return propertyName.replace(regex) { matchResult ->
        matchResult.groups[1]!!.value.toUpperCase()
      }
    }

    return propertyName
  }

  companion object {
    val regex = "_([a-z])".toRegex()
  }
}
```
